# ICTP-SFAIR/Serrapilheira
#
# Traingin Program inQuantitative Biology and Ecology
# Computational Methods
#
# Biodiversity databases
# Data cleaning

# Occurence downloads

# Packages ----

library(rgbif) # to retrieve data from gbif
library(Taxonstand) # to retrieve data from ...
library(CoordinateCleaner)
library(maps)
library(dplyr)

# Getting the data ----

# Download the data of a Primulaceae species from
# South America Myrsine coriacea (Sw.) R.Br.

species <- "Myrsine coriacea"

occur <- occ_search(scientificName = species,
                   limit = 100000) # retrieve GBIF occurences

# Column names returned from gbif follow the
# DarwinCore standard (https://dwc.tdwg.org).

names(occur)

# glimpse(occur)
# names(occur$data)

# The occurrences are saved in occs$data.
# Let’s create a new object from this table

myrsine_data <- occur$data

colnames(myrsine_data)

# Exporting raw data -----

# It is always important preserve the raw data
write.csv(myrsine_data,
          "data/raw/myrsine_data.csv",
          row.names = FALSE)


# Checking species taxonomy ----

sort(unique(myrsine_data$scientificName))
# Different scientific name because it changes over time

# In this particular case, we have a species with a long history of synonyms.
# In the gbif data, there is already a column showing the currently accepted taxonomy:

table(myrsine_data$taxonomicStatus)

# We can also check which of the names are accepted or not:

table(myrsine_data$scientificName,
      myrsine_data$taxonomicStatus)


## Checkin taxonomy with TPL ----

# Let’s use the function TPL() from package taxonstand
# to check if the taxonomic updates in the gbif data are correct.

# First generate a list with unique species names and combine it to the data
# No need to check the name more than once

species_names <- unique(myrsine_data$scientificName)
dim(species_names)

tax_check <- TPL(species_names)

# Note that the function adds several new variables to the input
# data and creates columns such as New.Genus and New.Species with
# the accepted name. We should adopt these names if the column
# New.Taxonomic.status is filled with “Accepted”

# We will merge the new genus and species and then add them to the original data

# creating new object w/ original and new names after TPL
new_tax <- data.frame(scientificName = species_names,
                      genus.new.TPL = tax_check$New.Genus,
                      species.new.TPL = tax_check$New.Species,
                      status.TPL = tax_check$Taxonomic.status,
                      scientificName.new.TPL = paste(tax_check$New.Genus,
                                                     tax_check$New.Species))

# now we are merging raw data and checked data

myrsine_new_tax <- merge(myrsine_data, new_tax, by = "scientificName")


## Exporting data after taxonomic check ----

# To guarantee the documentation of all steps, we will export the data after the taxonomy check.

write.csv(myrsine_new_tax,
          "data/processed/data_taxonomy_check.csv",
          row.names = FALSE)

# Checking specie coordinates ----

# First, inspect visually the coordinates in the raw data.

plot(decimalLatitude ~ decimalLongitude, data = myrsine_data, asp = 1)
map( , , , add = TRUE)

## Cleaning coordinates with clean_coordinate() ----

# This function checks for common errors in coordinates such as
# institutional coordinates, sea coordinates, outliers, zeros, centroids, etc.
# This function does not accept not available information (here addressed as “NA”)
# so we will first select only data that have a numerical value for both
# latitude and longitude.

myrsine_coord <- myrsine_data[!is.na(myrsine_data$decimalLatitude)
                              & !is.na(myrsine_data$decimalLongitude),]

# output w/ only potential correct coordinates
geo_clean <- clean_coordinates(x = myrsine_coord,
                               lon = "decimalLongitude",
                               lat = "decimalLatitude",
                               species = "species",
                               value = "clean")

dim(geo_clean)

# PLOT
par(mfrow = c(1, 2))

plot(decimalLatitude ~ decimalLongitude,
     data = myrsine_data, asp = 1)
map(, , , add = TRUE)

plot(decimalLatitude ~ decimalLongitude,
     data = geo_clean, asp = 1)
map(, , , add = TRUE)

par(mfrow = c(1, 1))

# When setting value = clean it returns only the potentially correct coordinates.
# For checking and reproducibility we want to save all the output with the flags
# generated by the routine. Let’s try a different output.

myrsine_new_geo <- clean_coordinates(x = myrsine_coord,
                                     lon = "decimalLongitude",
                                     lat = "decimalLatitude",
                                     species = "species",
                                     value = "spatialvalid")



# merging w/ original data



# merging w/ original data
myrsine_new_geo2 <- merge(myrsine_data, myrsine_new_geo,
                          all.x = TRUE,
                          by = "key")


plot(decimalLatitude.x ~ decimalLongitude.x, data = myrsine_new_geo2 , asp = 1)
map(, , , add = TRUE)


# HOMEWORK: Ploting with tmap and making an interactive map ----
library(sf)
library(tmap)

myrsine_sf <- st_as_sf(myrsine_new_geo,
                       coords = c("decimalLongitude",
                                  "decimalLatitude"),
                       crs=2163)


geo.clean.sf <- myrsine_new_geo %>%
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs=2163)
